### ISSUE TITLE
Error: The path '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/Classes/classes.jar' does not exist.

### ISSUE THREAD

**Issue by ericbodden** [CROSSINGTUD/CogniCrypt#151]
With the latest Beta, build 1.0.0.201802161202:
<details> 
  <summary>java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/Classes/classes.jar' does not exist.
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:223)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:706)
	at soot.asm.AsmClassProvider.find(AsmClassProvider.java:35)
	at soot.SourceLocator.getClassSource(SourceLocator.java:81)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:212)
	at soot.SootResolver.bringToSignatures(SootResolver.java:275)
	at soot.SootResolver.bringToBodies(SootResolver.java:313)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:166)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:873)
	at soot.Scene.loadClassAndSupport(Scene.java:858)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:67)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:53)
	at de.cognicrypt.staticanalyzer.handlers.AnalysisKickOff.run(AnalysisKickOff.java:98)
	at de.cognicrypt.staticanalyzer.handlers.StartupHandler$AfterBuildListener.resourceChanged(StartupHandler.java:93)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)</summary>
`Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/Classes/classes.jar' does not exist.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at soot.SourceLocator.getClassSourceType(SourceLocator.java:221)
	... 22 more
Caused by: java.lang.Exception: Error: The path '/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/Classes/classes.jar' does not exist.
	at soot.SourceLocator$2.load(SourceLocator.java:199)
	at soot.SourceLocator$2.load(SourceLocator.java:194)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	... 28 more
</details>

**Comment by kruegers** [comment]
This issue seems to have been resolved. One can now install CogniCrypt from the update site.
